/** Declaration file generated by dts-gen */

declare module '@liquality/cryptoassets' {
  export const assets: {
    '0xBTC': {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    '1ST': {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    '2KEY': {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    AAVE: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    ADX: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    ADXL: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    AE: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    AERGO: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    AION: {
      chain: string;
      code: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    AMLT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    AMPL: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    ANT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    ANTv1: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    APPC: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    ART: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    AST: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    ATRI: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    AUC: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    AXN: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    BAL: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    BAT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    BBK: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    BC: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    BCAP: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    BCPT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    BEE: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    BETHER: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    BLZ: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    BMX: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    BNB: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      decimals: number;
      name: string;
      type: string;
    };
    BNT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    BOA: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    BOB: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    BOOTY: {
      chain: string;
      code: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    BOX: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    BPRO: {
      chain: string;
      code: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    BTC: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      decimals: number;
      name: string;
      type: string;
    };
    BTU: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    BUSD: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    C10: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    C20: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    CAG: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    CAMP: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    CAN: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    CAT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    CEL: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    CELR: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    CHAI: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    CLN: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    COMP: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    CPLO: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    CRO: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    CVL: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    CVP: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    DAI: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    DANK: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    DATA: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    DAY: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    DCN: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    DGD: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    DGS: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    DIA: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    DKA: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    DNT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    DOC: {
      chain: string;
      code: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    DREAM: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    DSCP: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    DTH: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    EDG: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    ELF: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    ELY: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    ENG: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    ENJ: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    ENQ: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    ENTRP: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    ERT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    ETH: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      decimals: number;
      name: string;
      type: string;
    };
    EURS: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    EWTB: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    FET: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    FKX: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    FOAM: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    FRM: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    FTM: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    FUN: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    GAME: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    GEE: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    GEN: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    GET: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    GLA: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    GLM: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    GNO: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    GNT: {
      chain: string;
      code: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    GOLD: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    GOLDX: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    GRID: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    GUP: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    GUSD: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    HAK: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    HERC: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    HEX: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    HGT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    HOT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    HUNT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    HUSD: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    HYDRO: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    ICN: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    ICX: {
      chain: string;
      code: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    IDRT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    IMP: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    IND: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    IOST: {
      chain: string;
      code: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    IOTX: {
      chain: string;
      code: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    IQN: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    J8T: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    JET: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    JOY: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    KCS: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    KEY: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    KNC: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    KODA: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    KTON: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    LEDU: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    LEND: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    LGO: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    LIKE: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    LINK: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    LMY: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    LOOM: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    LPT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    LRC: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    LTO: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    LUN: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    LVN: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    MANA: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    MAS: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    MATIC: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    MET: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    METM: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    MFT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    MINDS: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    MITH: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    MKR: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    MLN: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    MOD: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    MTA: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    MTL: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    MTLX: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    MYB: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    NANJ: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    NCT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    NDC: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    NDX: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    NEAR: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      decimals: number;
      name: string;
      type: string;
    };
    NEEO: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    NEU: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    NEXO: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    NFC: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    NMR: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    NUSD: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    OCTO: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    OGN: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    OGO: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    OMG: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    ONE: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    ONL: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    ORBS: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    OST: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    OXT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    PARETO: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    PAX: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    PAXG: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    PKT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    PLA: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    PLAT: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    PLAY: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    PLDAI: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    PLR: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    PLSAI: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    PLU: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    PLUSDC: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    PNK: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    POA20: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    POLY: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    POP: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    POWR: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    PPT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    PROPS: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    QNT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    QSP: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    QTUM: {
      chain: string;
      code: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    RAE: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    RARI: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    RBTC: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      decimals: number;
      name: string;
      type: string;
    };
    RDN: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    RDOC: {
      chain: string;
      code: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    REDC: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    REMI: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    REN: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    REP: {
      chain: string;
      code: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    REPv2: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    REQ: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    REVV: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    RFR: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    RHOC: {
      chain: string;
      code: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    RIF: {
      chain: string;
      code: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    RIFP: {
      chain: string;
      code: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    RING: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    RLC: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    RMESH: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    ROCK2: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    ROOBEE: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    RVT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    SAI: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    SAN: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    SBTC: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    SETH: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    SIG: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    SKL: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    SKM: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    SNGLS: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    SNT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    SNTVT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    SNX: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    SOUL: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    SOV: {
      chain: string;
      code: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    SPANK: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    SPN: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    SPND: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    STAKE: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    STAR: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    STMX: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    STORJ: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    SUSD: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    SWM: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    SWT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    TAAS: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    TBTC: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    TIME: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    TKN: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    TLN: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    TOP: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    TRST: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    TUSD: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    UMA: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    UNI: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    UPX: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    USDC: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    USDN: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    USDT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    VDOC: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    VEN: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    VIDT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    VIEW: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    VSL: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    WAX: {
      chain: string;
      code: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    WBTC: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    WETH: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    WIB: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    WINGS: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    WIS: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    WTC: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    WYV: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    XAUR: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    XBP: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    XNK: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    XPR: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    XSC: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    YEED: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    YFDOT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    YFI: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    ZAP: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    ZCRT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    ZEON: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    ZIL: {
      chain: string;
      code: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    ZRX: {
      chain: string;
      code: string;
      coinGeckoId: string;
      color: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    aAAVE: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    aBAT: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    aBUSD: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    aDAI: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    aENJ: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    aKNC: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    aLINK: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    aMANA: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    aMKR: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    aREN: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    aSNX: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    aSUSD: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    aTUSD: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    aUNI: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    aUSDC: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    aUSDT: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    aWBTC: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    aWETH: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    aYFI: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    aZRX: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    cBAT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    cDAI: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    cETH: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    cREP: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    cSAI: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    cUSDC: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    cUSDT: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    cWBTC: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    cZRX: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    mUSD: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    rDAI: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    rSAI: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    renBCH: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    renBTC: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    renFIL: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    renZEC: {
      chain: string;
      code: string;
      coinGeckoId: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
    stAAVE: {
      chain: string;
      code: string;
      contractAddress: string;
      decimals: number;
      name: string;
      type: string;
    };
  };

  export const chains: {
    bitcoin: {
      code: string;
      fees: {
        unit: string;
      };
      formatAddress: any;
      formatTransactionHash: any;
      isValidAddress: any;
      isValidTransactionHash: any;
      name: string;
      nativeAsset: string;
      safeConfirmations: number;
    };
    bsc: {
      code: string;
      fees: {
        unit: string;
      };
      formatAddress: any;
      formatTransactionHash: any;
      isValidAddress: any;
      isValidTransactionHash: any;
      name: string;
      nativeAsset: string;
      safeConfirmations: number;
    };
    ethereum: {
      code: string;
      fees: {
        unit: string;
      };
      formatAddress: any;
      formatTransactionHash: any;
      isValidAddress: any;
      isValidTransactionHash: any;
      name: string;
      nativeAsset: string;
      safeConfirmations: number;
    };
    near: {
      code: string;
      fees: {
        unit: string;
      };
      formatAddress: any;
      formatTransactionHash: any;
      isValidAddress: any;
      isValidTransactionHash: any;
      name: string;
      nativeAsset: string;
      safeConfirmations: number;
    };
    rsk: {
      code: string;
      fees: {
        unit: string;
      };
      formatAddress: any;
      formatTransactionHash: any;
      isValidAddress: any;
      isValidTransactionHash: any;
      name: string;
      nativeAsset: string;
      safeConfirmations: number;
    };
  };

  export function currencyToUnit(e: any, t: any): any;

  export function unitToCurrency(e: any, t: any): any;
}
